/* This file was generated by SableCC (http://www.sablecc.org/). */

package naturel.node;

import java.util.*;
import naturel.analysis.*;

@SuppressWarnings("nls")
public final class AInterfaceInterface extends PInterface
{
    private final LinkedList<TIdentifier> _name_ = new LinkedList<TIdentifier>();

    public AInterfaceInterface()
    {
        // Constructor
    }

    public AInterfaceInterface(
        @SuppressWarnings("hiding") List<TIdentifier> _name_)
    {
        // Constructor
        setName(_name_);

    }

    @Override
    public Object clone()
    {
        return new AInterfaceInterface(
            cloneList(this._name_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInterfaceInterface(this);
    }

    public LinkedList<TIdentifier> getName()
    {
        return this._name_;
    }

    public void setName(List<TIdentifier> list)
    {
        this._name_.clear();
        this._name_.addAll(list);
        for(TIdentifier e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TIdentifier> i = this._name_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TIdentifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
