/* This file was generated by SableCC (http://www.sablecc.org/). */

package naturel.node;

import naturel.analysis.*;

@SuppressWarnings("nls")
public final class AMethodcalldefExp extends PExp
{
    private PExp _clazz_;
    private PExp _method_;

    public AMethodcalldefExp()
    {
        // Constructor
    }

    public AMethodcalldefExp(
        @SuppressWarnings("hiding") PExp _clazz_,
        @SuppressWarnings("hiding") PExp _method_)
    {
        // Constructor
        setClazz(_clazz_);

        setMethod(_method_);

    }

    @Override
    public Object clone()
    {
        return new AMethodcalldefExp(
            cloneNode(this._clazz_),
            cloneNode(this._method_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodcalldefExp(this);
    }

    public PExp getClazz()
    {
        return this._clazz_;
    }

    public void setClazz(PExp node)
    {
        if(this._clazz_ != null)
        {
            this._clazz_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._clazz_ = node;
    }

    public PExp getMethod()
    {
        return this._method_;
    }

    public void setMethod(PExp node)
    {
        if(this._method_ != null)
        {
            this._method_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._method_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._clazz_)
            + toString(this._method_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._clazz_ == child)
        {
            this._clazz_ = null;
            return;
        }

        if(this._method_ == child)
        {
            this._method_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._clazz_ == oldChild)
        {
            setClazz((PExp) newChild);
            return;
        }

        if(this._method_ == oldChild)
        {
            setMethod((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
