/* This file was generated by SableCC (http://www.sablecc.org/). */

package naturel.node;

import naturel.analysis.*;

@SuppressWarnings("nls")
public final class ANamedVariable extends PVariable
{
    private TIdentifier _name_;
    private PType _type_;
    private PExp _val_;

    public ANamedVariable()
    {
        // Constructor
    }

    public ANamedVariable(
        @SuppressWarnings("hiding") TIdentifier _name_,
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") PExp _val_)
    {
        // Constructor
        setName(_name_);

        setType(_type_);

        setVal(_val_);

    }

    @Override
    public Object clone()
    {
        return new ANamedVariable(
            cloneNode(this._name_),
            cloneNode(this._type_),
            cloneNode(this._val_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANamedVariable(this);
    }

    public TIdentifier getName()
    {
        return this._name_;
    }

    public void setName(TIdentifier node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public PExp getVal()
    {
        return this._val_;
    }

    public void setVal(PExp node)
    {
        if(this._val_ != null)
        {
            this._val_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._val_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._type_)
            + toString(this._val_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._val_ == child)
        {
            this._val_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TIdentifier) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._val_ == oldChild)
        {
            setVal((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
