/* This file was generated by SableCC (http://www.sablecc.org/). */

package naturel.node;

import java.util.*;
import naturel.analysis.*;

@SuppressWarnings("nls")
public final class ATupleType extends PType
{
    private final LinkedList<PVariable> _vars_ = new LinkedList<PVariable>();
    private PFlag _array_;

    public ATupleType()
    {
        // Constructor
    }

    public ATupleType(
        @SuppressWarnings("hiding") List<PVariable> _vars_,
        @SuppressWarnings("hiding") PFlag _array_)
    {
        // Constructor
        setVars(_vars_);

        setArray(_array_);

    }

    @Override
    public Object clone()
    {
        return new ATupleType(
            cloneList(this._vars_),
            cloneNode(this._array_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATupleType(this);
    }

    public LinkedList<PVariable> getVars()
    {
        return this._vars_;
    }

    public void setVars(List<PVariable> list)
    {
        this._vars_.clear();
        this._vars_.addAll(list);
        for(PVariable e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PFlag getArray()
    {
        return this._array_;
    }

    public void setArray(PFlag node)
    {
        if(this._array_ != null)
        {
            this._array_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._array_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vars_)
            + toString(this._array_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vars_.remove(child))
        {
            return;
        }

        if(this._array_ == child)
        {
            this._array_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PVariable> i = this._vars_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVariable) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._array_ == oldChild)
        {
            setArray((PFlag) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
