/* This file was generated by SableCC (http://www.sablecc.org/). */

package naturel.node;

import naturel.analysis.*;

@SuppressWarnings("nls")
public final class ATypeType extends PType
{
    private TIdentifier _name_;
    private PFlag _array_;

    public ATypeType()
    {
        // Constructor
    }

    public ATypeType(
        @SuppressWarnings("hiding") TIdentifier _name_,
        @SuppressWarnings("hiding") PFlag _array_)
    {
        // Constructor
        setName(_name_);

        setArray(_array_);

    }

    @Override
    public Object clone()
    {
        return new ATypeType(
            cloneNode(this._name_),
            cloneNode(this._array_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeType(this);
    }

    public TIdentifier getName()
    {
        return this._name_;
    }

    public void setName(TIdentifier node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public PFlag getArray()
    {
        return this._array_;
    }

    public void setArray(PFlag node)
    {
        if(this._array_ != null)
        {
            this._array_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._array_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._array_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._array_ == child)
        {
            this._array_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TIdentifier) newChild);
            return;
        }

        if(this._array_ == oldChild)
        {
            setArray((PFlag) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
