/* This file was generated by SableCC (http://www.sablecc.org/). */

package naturel.node;

import naturel.analysis.*;

@SuppressWarnings("nls")
public final class TBarEqual extends Token
{
    public TBarEqual()
    {
        super.setText("|=");
    }

    public TBarEqual(int line, int pos)
    {
        super.setText("|=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBarEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBarEqual(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBarEqual text.");
    }
}
