/* This file was generated by SableCC (http://www.sablecc.org/). */

package naturel.node;

import naturel.analysis.*;

@SuppressWarnings("nls")
public final class THashHash extends Token
{
    public THashHash()
    {
        super.setText("##");
    }

    public THashHash(int line, int pos)
    {
        super.setText("##");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THashHash(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHashHash(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THashHash text.");
    }
}
