/* Generated by Naturel. Do not modify. */
/* 1.0.0 - Sun Apr 06 13:52:35 CEST 2008 */

#ifndef _NATUREL_H
#define _NATUREL_H
#include "Core.h"

typedef struct SZufallsgenerator* Zufallsgenerator;
typedef struct SZahlenraten* Zahlenraten;
struct SZufallsgenerator {
	struct SObject super;
	num varClass_1;
	num varClass_2;
	num varClass_3;
	num varClass_4;
	num (*getRand)(Zufallsgenerator this);
};

struct SZahlenraten {
	struct SZufallsgenerator super;
	num varClass_5;
	void (*spiel)(Zahlenraten this);
};

Zufallsgenerator newZufallsgenerator();
void initZufallsgenerator(Zufallsgenerator this);
num Zufallsgenerator_getRand(Zufallsgenerator this);
Zufallsgenerator createZufallsgenerator();
Zahlenraten newZahlenraten(num varParam_11);
void initZahlenraten(Zahlenraten this, num varParam_11);
str Zahlenraten_tostr(Zahlenraten this);
void Zahlenraten_spiel(Zahlenraten this);
num Zahlenraten_main(list);
Zahlenraten createZahlenraten();
extern str varClass_6;
extern str varClass_7;
extern str varClass_8;
extern str varClass_9;
extern str varClass_10;
#endif
